#배포용

spring:
  datasource:
    url: jdbc:oracle:thin:@3.35.214.91:1521:xe
    username: tuthree1234
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver

  rabbitmq:
    host: localhost
    username: tuthree1234
    password: 1234
    port: 5672
    listener:
      simple:
        acknowledge-mode: none

  jpa:
    hibernate:
      ddl-auto: none

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
    port: 6379
    host: localhost

server:
  port: 8088

    #logging:
    #pattern:
    #console: %d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
  #level: debug
