spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Documents/IdeaProjects/TuthreeDatabase
    username: sa
    password:
    driver-class-name: org.h2.Driver
  rabbitmq:
    host: localhost
    username: tuthree1234
    password: 1234
    port: 5672
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
    port: 6379
    host: localhost
  jpa:
    hibernate:
      ddl-auto: create #create => none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
logging:
  level:
    #org.hibernate.SQL: debug # log
    org.hibernate.type: warn #query parameter | external library 사용 | spring-boot-datasource-decorator
    org.springframework.web: warn
    project.tuthree.ApiController: debug


