# oracle 사용자 생성 - database 생성
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: tuthreeadmin
    password: admin1234
    driver-class-name: oracle.jdbc.driver.OracleDriver

    #hikari:
      #schema: classpath:src/main/resources/schema.sql
  rabbitmq:
    host: localhost
    username: tuthree1234
    password: 1234
    port: 5672
  jpa:
    hibernate:
      ddl-auto: none
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
    port: 6379
    host: localhost

server:
  port: 8088
#logging:
#  level:
#    "[org.hibernate]": debug

